language: python
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - sh install.sh
  - CDVERSION=`curl http://chromedriver.storage.googleapis.com/LATEST_RELEASE`
  - wget http://chromedriver.storage.googleapis.com/$CDVERSION/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo chmod u+x chromedriver
  - sudo mv chromedriver /usr/bin/
install:
  # - pip install .
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
matrix:
  include:
    - python: "2.7" # For PR and cron
      env:
        - BROWSER=chrome
        - SELENIUM=3.4.1
        - ROBOTFRAMEWORK=3.0.2
before_script:
  # - "export DISPLAY=:99.0"
  # - "sh -e /etc/init.d/xvfb start"
  - pip install selenium==$SELENIUM
  - pip install robotframework==$ROBOTFRAMEWORK
  - pip install robotframework-selenium2library==1.7.4
script:
  - xvfb-run robot test.robot
